### ISSUE TITLE
Switch to new MathJax CDN or self-host

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book#114]
@SteveBarnett MathJax has just [announced](https://www.mathjax.org/cdn-shutting-down/) that they are shutting down their CDN, because they can't afford it any more. They recommend cdnjs, which means changing:

```
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/2.7-latest/MathJax.js?...">
</script>
```

to

```
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?...">
</script>
```

That is probably our best bet, but it does raise the issue of dependence on a provider for something quite central to our template. Should we consider alternatives? Should we make the MathJax CDN a config setting, to make it easier to switch in a given repo later?

I still think including MathJax with the template is unnecessary.

**Comment by SteveBarnett** [comment]
Hrm. There's also "We generally recommend switching to the CommonHTML and SVG outputs since the HTML-CSS output will be dropped from v3.0." which is relevant because [we use HTML-CSS for not-PDF outputs](https://github.com/electricbookworks/electric-book/blob/develop/_includes/mathjax-config#L32) (because of Phantom rendering IIRC).

I think just switching the CloudFlare CDN sounds like a good solution for now: big and reliable. And I don't see this as a thing that will be changed much, so it's not worth making it a setting. Using the MathJax CDN we already have a dependency on a provider, so we're not making the situation worse: just moving sideways.

We should have a bigger talk about dependencies in general (like elasticlunr for the search) which will tie in a bit to [upgrade path](https://github.com/electricbookworks/electric-book/issues/57).

**Comment by arthurattwell** [comment]
@SteveBarnett Yeah, sensible. I've pushed #115 for the CDN change.

I think we were using HTML-CSS because of EPUB2, which doesn't support SVG. Though I'd need to revisit and test web output to see whether there were issues there, but I doubt there would be.
