### ISSUE TITLE
Paragraph break in valediction

### ISSUE THREAD

**Issue by tgraham-antenna** [electricbookworks/electric-book#607]
From https://github.com/electricbookworks/electric-book/blob/2360e6f25ed5cb35ace7295ee9d53333f2bff4e0/samples/text/01-01-plain-text.md?plain=1#L593:

```
> <!-- index: -Adler, Irene -->"Very truly yours,\\
> "IRENE NORTON, née ADLER."
> {:.valediction}
```

The leading `"` in `"IRENE NORTON, née ADLER."` indicates that it starts a new paragraph, not a new line.

**Comment by arthurattwell** [comment]
Housekeeping long-unattended issues. Thank you, @tgraham-antenna.

This one is a digitiser's dilemma: you're quite right that grammatically there is a new para here. Valedictions at the ends of letters take so many different forms, and for our default, vanilla template styles I wanted to create [a CSS style](https://github.com/electricbookworks/electric-book/blob/master/_sass/template/partials/_web-letters.scss#L12) that is as simple and unopinionated as possible, and that meant assuming that the most common valedictions comprise a single paragraph with line breaks. That's why we've digitised this one with a line break. If we were doing a bespoke book with a custom design and digitisation guide, we'd probably create a more sophisticated (and opinionated) HTM structure for valedictions.
