### ISSUE TITLE
screen-pdf or print-pdf for KDP print on demand?

### ISSUE THREAD

**Issue by jaycolmvar** [electricbookworks/electric-book#624]
This is really a question rather than an issue per se, but anyway:

I'm thinking about doing a Kindle Direct Publishing print on demand paperback edition (in addition to a Kindle edition), but I'm unclear on how I should produce the PDF for the KDP paperback.

KDP guidelines specifically say not to include printer marks, which the print-pdf version has, so I figured I would use the screen-pdf version instead. (I'd remove the cover page, of course, since that would need to be submitted separately.) However I'm not sure if the screen-pdf version would cause problems in other areas, like margins being too small once the book is trimmed.

Any advice?

P.S. I've been having good luck with EB lately, especially after updating to HEAD. In particular, my EPUB output file is validating totally clean with epubcheck 4.2.6, and also converts using Kindle Previewer 3 with zero errors. Thanks for all the hard work you all have put into this!

**Comment by jaycolmvar** [comment]
Actually, it looks as if I may have answered my own question: Looking at the EB documentation I see that there's a setting $print-page-setup-lightning-source in print-pdf.scss that removes the crop marks and adds 3mm of extra margin. I tried this out and it works as advertised.

Is this what people recommend for PDF files to be submitted to KDP print on demand?

**Comment by jaycolmvar** [comment]
My aplogies for following up my own comment again, but: I noticed that setting $print-page-setup-lightning-source to true in print-pdf.scss also seems to increase the margins for screen-pdf, at least for the cover.

**Comment by arthurattwell** [comment]
Thanks, @jaycolmvar! You're quite right that the place to start is `$print-page-setup-lightning-source: true`. As the variable's name suggests, we created those CSS settings for LightningSource (i.e. Ingram). We have very little experience with Amazon's requirements, so I can't be sure they'll work for both. I imagine we might need Amazon-specific CSS if the LS settings don't meet Amazon's requirements.

You may have found a bug if `$print-page-setup-lightning-source` is breaking the cover in screen PDF. We're generally set `$print-page-setup-lightning-source: true` just temporarily when generating a print-PDF, so I imagine we've never actually tested and debugged the effect on screen-PDF output. 

I'll leave this issue open for that bug, because it would be best if `$print-page-setup-lightning-source` only affected print-PDF output.

**Comment by jaycolmvar** [comment]
Following up on this issue after trying this again. I think what caused the problem last time with this variable affecting the screen-pdf output is that I set `$print-page-setup-lightning-source: true` in `_sass/template/print-pdf.scss`.

I tried again, setting it to `true` in `book/styles/print-pdf.scss`, and leaving `_sass/template/print-pdf.scss` alone. This changed the print-pdf output, but the screen-pdf output appeared unchanged.

Given the above, I think you can close this issue. The only thing you might want to do is clarify the document to emphasize that changes to this variable should be made in the `styles/print-pdf.scss` file. (Right now the documentation just refers to the `print-pdf.scss` file, which exists in two places.)
