### ISSUE TITLE
Speed up build and regeneration

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/electric-book#92]
On another project, we have a lot of Liquid looping, which makes builds really slow. This problem affects any project with a long menu, so it's a challenge we should address here in the template.

@SteveBarnett Can you copy any relevant findings and thoughts from that project here, please?

I work on Windows, where my build times seem to be 10-20% slower than unix systems. But the main problem on Windows is that `--incremental` isn't reliable. Occasionally it works, and it's amazing. But I'll often make a CSS change and wait 300 seconds for regeneration. And sometimes Jekyll doesn't regenerate at all, as if it doesn't see the file change. I've not investigated whether there is a pattern to this behaviour.

I don't think we should be going to great lengths to solve a Windows-specific problem with `--incremental` though. I think we should work out some best practices for Liquid loops. This might take two forms: one, just being smarter about how data is structured and looped through -- it's quite conceivable my looping is inefficient. Two, maybe we'll hit on a clever way to generate hashes of page-specific variables once, then output them on pages as output tags, saving repeated loops on every page. I've not applied my mind to whether that's even possible, though.

**Comment by SteveBarnett** [comment]
On sites of ours that are slow to build, the initial `jekyll build` can be long (minutes instead of seconds). Running with `--incremental` brings subsequent builds (and serves) down to a few seconds if you change a `/ book/text` file, but stays high if you change an include like `nav`.

Some quick googling suggests that OOTB Jekyll is fast, but Windows, your Ruby version, Jekyll Plugins, and complicated Liquid can slow it down. It seems like Liquid is our main culprit. New in Jekyll 3 is `--profile`, which shows Count, Bytes, and Time for Liquid and can help us identify specific problem files. 

The number of files (perhaps obviously) changes this a lot. It seems that hitting around 100 files has a bit of a performance spike.

**Comment by SteveBarnett** [comment]
The short-term solution to faster builds seems to be:

- use `--incremental`;
- don't change things like `_includes/nav.html` that touch a lot of files.

The long term solution is:

- dramatically simplify the Liquid in the templates.

---

For Windows machines where `--incremental` support can be patchy, the slow-build-every-time problem can be mitigated by extensive use of `exclude` and `keep_files` in the `_config.yml`.

A strange sidenote: make sure you use a file extension in the `exclude` array: if you don't (e.g. you use a wildcard), the `build` still gets triggered when you change the file ¯\\\_(ツ)_/¯. Wildcards in `keep_files` seem to work fine.

(And don't forget that `exclude`'s path are [relative to the output directory](https://jekyllrb.com/docs/configuration/#global-configuration), so use `book/text/my-file.md`)

**Comment by SteveBarnett** [comment]
@arthurattwell Should we close this and add a new issue "review liquid" or similar?

**Comment by arthurattwell** [comment]
@SteveBarnett Sure, new issue #106 created.

**Comment by arthurattwell** [comment]
Big improvements made in #241.
